name: Build Geonix41

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install QMK CLI
        run: |
          python3 -m pip install qmk

      - name: Setup QMK
        run: |
          qmk setup -y .

      - name: Compile
        run: |
          qmk compile -kb geonix41/geonix41_oss -km vial

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            *.uf2
            *.bin
            *.hex
